server:
  port: 8086
spring:
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#    default-property-inclusion: non_null  # 序列化时过滤为null的属性
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: 192.168.146.140:9200

#  rabbitmq:
#    host: 106.54.238.192
#    username: gmall
#    password: gmall
#    virtual-host: /gmall
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 10000