server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.146.140
  rabbitmq:
    host: 192.168.146.140
    username: lvym
    password: tbny1312
    virtual-host: /lvym
gmall:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    UserKey: user-key

