server:
  port: 8888
spring:
  application:
    name: gmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-server
          predicates:
            - Path=/pms/**
          filters:
            - Auth
        - id: wms-route
          uri: lb://wms-server
          predicates:
            - Path=/wms/**
          filters:
            - Auth
        - id: sms-route
          uri: lb://sms-server
          predicates:
            - Path=/sms/**
          filters:
            - Auth
        - id: oms-route
          uri: lb://oms-server
          predicates:
            - Path=/oms/**
          filters:
            - Auth
        - id: ums-route
          uri: lb://ums-server
          predicates:
            - Path=/ums/**
          filters:
            - Auth
        - id: index-route
          uri: lb://index-server
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
            - Auth
        - id: order-route
          uri: lb://order-server
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
            - Auth  #自定义的拦截器
  main:
    allow-bean-definition-overriding: true

gmall:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
